Managed to use it to add some basic stuff! I received a really interesting error when trying to use it for add two strings:
main.cpp: In instantiation of ‘T add(T, T) [with T = const char*]’:
main.cpp:19:50:   required from here
main.cpp:33:15: error: invalid operands of types ‘const char*’ and
‘const char*’ to binary ‘operator+’
     return v1 + v2;

I realize that string literals are really just "c-strings", which I
suppose are really just char[]s, so I ended up just passing an
intialized string object off of the literal, and it's running!